const $=id=>document.getElementById(id);
let gallery=[],manual=[],editingId=null,dragSource=null,mediaTarget='gallery',mediaCandidates=[],mediaSelected=new Set();
const lists={highlights:[],differences:[],box:[],notIncluded:[],pros:[],considerations:[],faq:[],references:[]};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showMessage(title,message){$('dialogTitle').textContent=title;$('dialogMessage').textContent=message;$('messageDialog').showModal()}
$('dialogClose').onclick=()=>$('messageDialog').close();
function setDirty(text='มีการแก้ไขยังไม่บันทึก'){$('saveState').textContent=text;$('saveState').style.color='var(--red)'}
document.addEventListener('input',()=>setDirty());
function emptyRow(type){if(type==='differences')return {title:'',detail:''};if(type==='faq')return {q:'',a:''};if(type==='references')return {label:'',url:''};return ''}
function renderList(type){
 const map={highlights:'highlightsList',differences:'differencesList',box:'boxContentsList',notIncluded:'notIncludedList',pros:'prosList',considerations:'considerationsList',faq:'faqList',references:'referencesList'};
 const el=$(map[type]),data=lists[type];
 if(['differences','faq','references'].includes(type)){
  el.innerHTML=data.map((x,i)=> type==='differences'?`<div class="pair-row"><input data-list="${type}" data-i="${i}" data-key="title" value="${esc(x.title)}" placeholder="ชื่อหัวข้อ"><textarea data-list="${type}" data-i="${i}" data-key="detail" placeholder="รายละเอียด">${esc(x.detail)}</textarea><button class="remove-row" data-remove="${type}" data-i="${i}">ลบ</button></div>`:type==='faq'?`<div class="pair-row"><input data-list="${type}" data-i="${i}" data-key="q" value="${esc(x.q)}" placeholder="คำถาม"><textarea data-list="${type}" data-i="${i}" data-key="a" placeholder="คำตอบ">${esc(x.a)}</textarea><button class="remove-row" data-remove="${type}" data-i="${i}">ลบ</button></div>`:`<div class="reference-row"><input data-list="${type}" data-i="${i}" data-key="label" value="${esc(x.label)}" placeholder="ชื่อแหล่งอ้างอิง"><input data-list="${type}" data-i="${i}" data-key="url" value="${esc(x.url)}" placeholder="URL"><button class="remove-row" data-remove="${type}" data-i="${i}">ลบ</button></div>`).join('');
 } else {
  el.innerHTML=data.map((x,i)=>`<div class="repeat-row"><input data-list="${type}" data-i="${i}" value="${esc(x)}" placeholder="${type==='box'?'ชื่ออุปกรณ์':type==='notIncluded'?'รายการที่ไม่มีในกล่อง':'กรอกข้อความ'}"><button class="remove-row" data-remove="${type}" data-i="${i}">ลบ</button></div>`).join('');
 }
}
function add(type){lists[type].push(emptyRow(type));renderList(type);setDirty()}
document.addEventListener('click',e=>{const type=e.target.dataset.add;if(type){add(type);return}const rem=e.target.dataset.remove;if(rem){lists[rem].splice(Number(e.target.dataset.i),1);renderList(rem);setDirty()}});
document.addEventListener('input',e=>{const type=e.target.dataset.list;if(!type)return;const i=Number(e.target.dataset.i),key=e.target.dataset.key;if(key)lists[type][i][key]=e.target.value;else lists[type][i]=e.target.value});
function initializeRows(){['highlights','differences','box','notIncluded','pros','considerations','faq','references'].forEach(t=>{if(!lists[t].length)add(t)});$('saveState').textContent='เทมเพลตเปล่า';$('saveState').style.color=''}

document.querySelectorAll('.edit-block').forEach(btn=>btn.onclick=()=>{const block=btn.closest('.template-block');block.classList.add('editing');block.querySelectorAll('[contenteditable]').forEach(x=>x.contentEditable='true');block.querySelector('input,textarea,[contenteditable="true"]')?.focus()});
document.querySelectorAll('.save-block').forEach(btn=>btn.onclick=async()=>{const block=btn.closest('.template-block');block.classList.remove('editing');block.querySelectorAll('[contenteditable]').forEach(x=>x.contentEditable='false');await saveItem(false)});

async function compressImage(file,max=1100,quality=.74){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{let w=img.width,h=img.height;if(Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(c.toDataURL('image/webp',quality))};img.onerror=reject;img.src=url})}
async function addFiles(files,target){for(const f of [...files].filter(x=>x.type.startsWith('image/'))){const src=await compressImage(f,target==='manual'?1400:1100,target==='manual'?.76:.74);(target==='manual'?manual:gallery).push({src,name:f.name})}renderImages(target);setDirty('เพิ่มรูปแล้ว · ยังไม่บันทึก')}
function renderImages(target){const arr=target==='manual'?manual:gallery,thumbs=$(target==='manual'?'manualThumbs':'galleryThumbs'),main=$(target==='manual'?'mainManualImg':'mainProductImg'),placeholder=$(target==='manual'?'manualPlaceholder':'coverPlaceholder');if(arr.length){main.src=arr[0].src;main.hidden=false;placeholder.hidden=true}else{main.hidden=true;placeholder.hidden=false}thumbs.innerHTML=arr.map((x,i)=>`<span class="thumb-wrap" draggable="true" data-target="${target}" data-i="${i}"><img src="${x.src}" data-index="${i}" class="${i===0&&target==='gallery'?'cover-thumb':''}" alt="${esc(x.name)}">${i===0&&target==='gallery'?'<span class="cover-chip">COVER</span>':''}<button class="thumb-delete" data-image-remove="${target}" data-i="${i}">×</button></span>`).join('');thumbs.querySelectorAll('img').forEach(img=>img.onclick=()=>{main.src=arr[Number(img.dataset.index)].src;thumbs.querySelectorAll('img').forEach(x=>x.classList.remove('active'));img.classList.add('active')})}
$('uploadGalleryButton').onclick=()=>$('galleryInput').click();$('uploadManualButton').onclick=()=>$('manualInput').click();$('galleryInput').onchange=e=>addFiles(e.target.files,'gallery');$('manualInput').onchange=e=>addFiles(e.target.files,'manual');
for(const [drop,target] of [[$('galleryDrop'),'gallery'],[$('manualDrop'),'manual']]){drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');addFiles(e.dataTransfer.files,target)}}
document.addEventListener('click',e=>{const target=e.target.dataset.imageRemove;if(!target)return;(target==='manual'?manual:gallery).splice(Number(e.target.dataset.i),1);renderImages(target);setDirty()});
document.addEventListener('dragstart',e=>{const w=e.target.closest('.thumb-wrap');if(w)dragSource={target:w.dataset.target,index:Number(w.dataset.i)}});document.addEventListener('dragover',e=>{if(e.target.closest('.thumb-wrap'))e.preventDefault()});document.addEventListener('drop',e=>{const w=e.target.closest('.thumb-wrap');if(!w||!dragSource||w.dataset.target!==dragSource.target)return;e.preventDefault();const arr=w.dataset.target==='manual'?manual:gallery;const [m]=arr.splice(dragSource.index,1);arr.splice(Number(w.dataset.i),0,m);renderImages(w.dataset.target);dragSource=null;setDirty()});
function val(id){return $(id).value.trim()}function num(id){return val(id)===''?null:Number(val(id))}
function payload(){return {id:val('itemId'),sku:val('itemSku')||val('itemId').toUpperCase(),name:val('name'),category:'model',categoryLabel:'Gundam',categoryCode:'gd',productType:val('productType'),productTypeCode:'gp',line:'RG',lineCode:'rg',grade:'RG',seriesGroup:val('seriesGroup')||'Gundam',seriesGroupOrder:0,rgNumber:num('rgNumber'),modelCode:val('modelCode'),manufacturer:val('manufacturer'),series:val('series'),scale:val('scale'),releaseDate:val('releaseDate'),launchPriceJPY:num('launchPriceJPY'),heightCm:num('heightCm'),recommendedAge:val('recommendedAge'),material:val('material'),images:gallery.map(x=>x.src),catalogImage:gallery[0]?.src||'',videoEmbedUrl:val('videoEmbedUrl'),summary:$('summary').textContent.trim(),highlights:lists.highlights.filter(Boolean),whatsDifferent:lists.differences.filter(x=>x.title||x.detail),boxContents:lists.box.filter(Boolean),notIncluded:lists.notIncluded.filter(Boolean),pros:lists.pros.filter(Boolean),considerations:lists.considerations.filter(Boolean),faq:lists.faq.filter(x=>x.q||x.a),references:lists.references.filter(x=>x.label||x.url),sourceName:lists.references[0]?.label||'',sourceUrl:lists.references[0]?.url||'',affiliateLinks:{shopee:val('shopee'),lazada:val('lazada'),tiktok:val('tiktok'),page:val('pageLink')},manualImages:manual.map(x=>x.src),priceTaxIncluded:false,status:val('status'),catalogStatus:val('status')==='published'?'published':'draft',sortOrder:num('rgNumber')||0,mergeMode:'preserve-existing'}}
async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(r.status===401){location.href='/admin/';throw Error('กรุณาเข้าสู่ระบบใหม่')}if(!r.ok)throw Error(d.error||'เกิดข้อผิดพลาด');return d}
async function saveItem(show=true,forceStatus=''){const p=payload();if(forceStatus){p.status=forceStatus;p.catalogStatus=forceStatus==='published'?'published':'draft';$('status').value=forceStatus}if(!p.id){if(show)showMessage('ยังไม่มีรหัสรายการ','กรุณากรอกรหัสรายการก่อนบันทึก รหัสนี้ใช้สร้าง URL เช่น #/product/rg-039');return false}try{$('saveState').textContent='กำลังบันทึก…';let useId=editingId; if(!useId){try{await api(`/api/admin/catalog/${encodeURIComponent(p.id)}`);useId=p.id}catch(e){if(!String(e.message).includes('ไม่พบรายการ'))throw e}} const url=useId?`/api/admin/catalog/${encodeURIComponent(useId)}`:'/api/admin/catalog';await api(url,{method:useId?'PUT':'POST',body:JSON.stringify(p)});editingId=p.id;$('itemId').disabled=true;$('saveState').textContent=p.status==='published'?'เผยแพร่แล้ว':'บันทึกฉบับร่างแล้ว';$('saveState').style.color='var(--blue)';if(show)showMessage('บันทึกสำเร็จ',p.status==='published'?`เผยแพร่ ${p.id} แล้ว`:`บันทึกฉบับร่าง ${p.id} แล้ว ข้อมูลเดิมในช่องที่ไม่ได้กรอกจะยังอยู่`);return true}catch(e){showMessage('บันทึกไม่สำเร็จ',e.message);$('saveState').textContent='บันทึกไม่สำเร็จ';return false}}
$('saveAllButton').onclick=()=>saveItem(true,'draft');$('publishButton').onclick=()=>saveItem(true,'published');$('previewButton').onclick=()=>{const p=payload();localStorage.setItem('toyskub_catalog_preview',JSON.stringify(p));window.open('/#/product-preview','_blank')};
async function loadFromQuery(){const id=new URLSearchParams(location.search).get('id');if(!id)return;try{const d=await api(`/api/admin/catalog/${encodeURIComponent(id)}`);fill(d.item);editingId=id;$('itemId').disabled=true;$('saveState').textContent=`กำลังแก้ไข ${id}`}catch(e){showMessage('เปิดรายการไม่ได้',e.message)}}
function fill(p){$('itemId').value=p.id||'';$('itemSku').value=p.sku||'';$('seriesGroup').value=p.seriesGroup||'Gundam';$('status').value=p.status||'draft';$('name').value=(p.name==='ยังไม่ระบุชื่อ'?'':(p.name||''));$('summary').textContent=p.summary||'';for(const id of ['rgNumber','modelCode','manufacturer','series','scale','releaseDate','launchPriceJPY','heightCm','recommendedAge','productType','material','videoEmbedUrl'])$(id).value=p[id]??'';$('shopee').value=p.affiliateLinks?.shopee||'';$('lazada').value=p.affiliateLinks?.lazada||'';$('tiktok').value=p.affiliateLinks?.tiktok||'';$('pageLink').value=p.affiliateLinks?.page||'';gallery=(p.images||[]).map((src,i)=>({src,name:`รูป ${i+1}`}));manual=(p.manualImages||[]).map((src,i)=>({src,name:`คู่มือ ${i+1}`}));Object.assign(lists,{highlights:p.highlights||[],differences:p.whatsDifferent||[],box:p.boxContents||[],notIncluded:p.notIncluded||[],pros:p.pros||[],considerations:p.considerations||[],faq:p.faq||[],references:p.references||[]});Object.keys(lists).forEach(renderList);renderImages('gallery');renderImages('manual')}

function fileNameFromUrl(src){try{return decodeURIComponent(String(src).split('/').pop().split('?')[0])}catch{return String(src)}}
function normalizeAssetUrl(src){const v=String(src||'').trim();if(!v)return '';if(v.startsWith('data:')||v.startsWith('http://')||v.startsWith('https://')||v.startsWith('/'))return v;return '/'+v.replace(/^\.\//,'')}
async function openMediaLibrary(target){mediaTarget=target;mediaCandidates=[];mediaSelected.clear();$('mediaGrid').innerHTML='';$('mediaCatalogInfo').textContent='';$('mediaSelectedCount').textContent='เลือกแล้ว 0 รูป';$('mediaCatalogId').value=val('itemId')||'rg-039';$('mediaDialog').showModal();await loadCatalogMedia()}
async function loadCatalogMedia(){const id=$('mediaCatalogId').value.trim().toLowerCase();if(!id){$('mediaCatalogInfo').textContent='กรอกรหัสรายการก่อน';return}try{$('mediaCatalogInfo').textContent='กำลังโหลด…';let item=null;const local=await fetch(`/data/catalog/gundam/gunpla/rg/${encodeURIComponent(id)}.json`,{cache:'no-store'});if(local.ok)item=await local.json();if(!item){const dynamic=await fetch(`/api/admin/catalog/${encodeURIComponent(id)}`,{cache:'no-store'});if(dynamic.ok)item=(await dynamic.json()).item}if(!item)throw Error('ไม่พบข้อมูลแคตตาล็อก '+id);const sources=mediaTarget==='manual'?(item.manualImages||[]):[...(item.images||[]),...(item.catalogImage?[item.catalogImage]:[])];mediaCandidates=[...new Set(sources.filter(Boolean))];$('mediaCatalogInfo').textContent=`${item.name||id} · ${mediaCandidates.length} รูป`;renderMediaGrid()}catch(e){$('mediaCatalogInfo').textContent=e.message;$('mediaGrid').innerHTML='<div class="empty-state">ไม่พบรูปในรายการนี้</div>'}}
function renderMediaGrid(){$('mediaGrid').innerHTML=mediaCandidates.map((src,i)=>`<button class="media-card ${mediaSelected.has(i)?'selected':''}" data-media-index="${i}" type="button"><span class="media-check">✓</span><img src="${esc(normalizeAssetUrl(src))}" alt=""><small>${esc(fileNameFromUrl(src))}</small></button>`).join('');$('mediaSelectedCount').textContent=`เลือกแล้ว ${mediaSelected.size} รูป`}
$('catalogGalleryButton').onclick=()=>openMediaLibrary('gallery');$('catalogManualButton').onclick=()=>openMediaLibrary('manual');$('mediaClose').onclick=()=>$('mediaDialog').close();$('mediaLoad').onclick=loadCatalogMedia;$('mediaGrid').onclick=e=>{const card=e.target.closest('[data-media-index]');if(!card)return;const i=Number(card.dataset.mediaIndex);mediaSelected.has(i)?mediaSelected.delete(i):mediaSelected.add(i);renderMediaGrid()};$('mediaUseSelected').onclick=()=>{const chosen=[...mediaSelected].sort((a,b)=>a-b).map(i=>({src:normalizeAssetUrl(mediaCandidates[i]),name:fileNameFromUrl(mediaCandidates[i])}));if(!chosen.length){showMessage('ยังไม่ได้เลือกรูป','เลือกรูปอย่างน้อย 1 รูป');return}const arr=mediaTarget==='manual'?manual:gallery;const existing=new Set(arr.map(x=>x.src));chosen.forEach(x=>{if(!existing.has(x.src))arr.push(x)});renderImages(mediaTarget);setDirty('เลือกรูปจากแคตตาล็อกแล้ว · ยังไม่บันทึก');$('mediaDialog').close()};

initializeRows();loadFromQuery();
