const $=id=>document.getElementById(id);let products=[],orders=[],editingId='';
const esc=value=>String(value??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=value=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(value)||0);
const publicProductPath=id=>`/stock/onepiececard/${encodeURIComponent(String(id||'').trim().toLowerCase())}`;
const isPublicProduct=p=>p&&['published','sold_out'].includes(p.status);
function msg(text='',type='success',target='message'){const el=$(target);el.textContent=text;el.className=text?`status ${type}`:'status hidden'}
async function api(url,options={}){const response=await fetch(url,{cache:'no-store',credentials:'same-origin',...options,headers:{...(options.body&&typeof options.body==='string'?{'content-type':'application/json'}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401){location.href='/admin/';throw Error('กรุณาเข้าสู่ระบบใหม่')}if(!response.ok)throw Error(data.error||'เกิดข้อผิดพลาด');return data}
async function optimizeImage(file){try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));if(!blob)return file;return new File([blob],`${file.name.replace(/\.[^.]+$/,'')||'product'}.webp`,{type:'image/webp'})}catch{return file}}
function renderProducts(){$('productRows').innerHTML=products.length?products.map(p=>`<tr><td>${p.imageUrl?`<img class="thumb" src="${esc(p.imageUrl)}" alt="">`:'—'}</td><td><b>${esc(p.id)}</b><br>${esc(p.name)}${p.level?`<small>ระดับ: ${esc(p.level)}</small>`:''}<small>${esc(p.description)}</small><small class="product-path">${esc(publicProductPath(p.id))}</small></td><td>${money(p.price)}<small>ทุน ${money(p.costPrice)}</small></td><td>${p.stockQuantity} / ${p.reservedQuantity}<small>พร้อมขาย ${p.availableStock}</small></td><td><span class="status-pill ${esc(p.status)}">${p.availableStock===0?'Sold out':esc(p.status)}</span></td><td><div class="row-actions"><button data-edit="${esc(p.id)}">แก้ไข</button>${isPublicProduct(p)?`<a href="${esc(publicProductPath(p.id))}" target="_blank" rel="noopener">หน้าบ้าน ↗</a>`:'<span class="public-disabled">ยังไม่เผยแพร่</span>'}</div></td></tr>`).join(''):'<tr><td colspan="6">ยังไม่มีสินค้า</td></tr>'}
const transitionButtons=o=>o.status==='pending'?`<button data-order="${o.id}" data-status="payment_review">รับหลักฐานแล้ว</button><button data-order="${o.id}" data-status="cancelled">ยกเลิก</button>`:o.status==='payment_review'?`<button data-order="${o.id}" data-status="paid">ยืนยันชำระเงิน</button><button data-order="${o.id}" data-status="cancelled">ยกเลิก</button>`:'—';
function renderOrders(){$('orderRows').innerHTML=orders.length?orders.map(o=>`<tr><td><b>${esc(o.reference)}</b><small>${esc(o.createdAt)}</small></td><td><a class="order-product-link" href="${esc(publicProductPath(o.productId))}" target="_blank" rel="noopener">${esc(o.productName)} ↗</a><small>${o.quantity} × ${money(o.unitPrice)}</small><div class="shipping"><b>${esc(o.customerName)}</b> · ${esc(o.customerPhone)}<br>${esc(o.shippingAddress)}${o.customerNote?`<br>หมายเหตุ: ${esc(o.customerNote)}`:''}</div></td><td>${money(o.total)}</td><td><span class="status-pill ${esc(o.status)}">${esc(o.status)}</span></td><td><div class="order-actions">${transitionButtons(o)}</div></td></tr>`).join(''):'<tr><td colspan="5">ยังไม่มีคำสั่งซื้อ</td></tr>'}
async function load(){msg('กำลังโหลด…','loading');const [p,o]=await Promise.all([api('/api/admin/store/products'),api('/api/admin/store/orders')]);products=p.products||[];orders=o.orders||[];renderProducts();renderOrders();msg()}
function syncPublicProductLink(p=null){const id=(editingId||$('productId').value).trim().toLowerCase();const path=id?publicProductPath(id):'/stock/onepiececard/';$('productPublicUrl').value=path;const link=$('openPublicProduct');if(id&&isPublicProduct(p)){link.href=path;link.classList.remove('hidden')}else{link.href='#';link.classList.add('hidden')}}
function openForm(p=null){editingId=p?.id||'';$('productForm').reset();$('productId').value=p?.id||'';$('productId').disabled=Boolean(p);$('productName').value=p?.name||'';$('productDescription').value=p?.description||'';$('productPrice').value=p?.price??0;$('productCostPrice').value=p?.costPrice??0;$('productStock').value=p?.stockQuantity??0;$('productStatus').value=p?.status||'draft';$('productLevel').value=p?.level||'';$('imageUrl').value=p?.imageUrl||'';$('imageStatus').textContent=p?.imageUrl||'รองรับรูปไม่เกิน 8 MB';$('formTitle').textContent=p?'แก้ไขสินค้า':'เพิ่มสินค้า';syncPublicProductLink(p);msg('','','formMessage');$('productDialog').showModal()}
async function uploadIfNeeded(id){const file=$('productImage').files[0];if(!file)return $('imageUrl').value;if(!file.type.startsWith('image/')||file.size>8*1024*1024)throw Error('รูปต้องเป็นไฟล์ภาพขนาดไม่เกิน 8 MB');$('imageStatus').textContent='กำลังเตรียมและอัปโหลดรูป…';const display=await optimizeImage(file);const form=new FormData();form.append('file',display);form.append('id',id);form.append('kind','store');const data=await api('/api/admin/media/upload',{method:'POST',body:form});$('imageStatus').textContent='อัปโหลดรูปสำเร็จ';return data.url}
$('newProduct').addEventListener('click',()=>openForm());$('closeProduct').addEventListener('click',()=>$('productDialog').close());$('cancelProduct').addEventListener('click',()=>$('productDialog').close());
$('productId').addEventListener('input',()=>syncPublicProductLink());
$('productRows').addEventListener('click',event=>{const id=event.target.dataset.edit;if(id)openForm(products.find(p=>p.id===id))});
$('productForm').addEventListener('submit',async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{const id=(editingId||$('productId').value).trim().toLowerCase();const current=products.find(p=>p.id===editingId);const imageUrl=await uploadIfNeeded(id);const payload={id,name:$('productName').value,description:$('productDescription').value,level:$('productLevel').value,price:Number($('productPrice').value),costPrice:Number($('productCostPrice').value),stockQuantity:Number($('productStock').value),status:$('productStatus').value,sortOrder:current?.sortOrder??0,imageUrl};await api(editingId?`/api/admin/store/products/${encodeURIComponent(editingId)}`:'/api/admin/store/products',{method:editingId?'PUT':'POST',body:JSON.stringify(payload)});$('productDialog').close();await load();msg('บันทึกสินค้าเรียบร้อย')}catch(error){msg(error.message,'error','formMessage')}finally{submit.disabled=false}});
$('refreshOrders').addEventListener('click',load);
$('orderRows').addEventListener('click',async event=>{const id=Number(event.target.dataset.order),status=event.target.dataset.status;if(!id||!status)return;if(status==='paid'&&!confirm('ยืนยันว่าได้รับเงินจริงและตัดสต็อกหรือไม่?'))return;event.target.disabled=true;try{await api(`/api/admin/store/orders/${id}`,{method:'PUT',body:JSON.stringify({status})});await load();msg(`อัปเดตคำสั่งซื้อเป็น ${status} แล้ว`)}catch(error){msg(error.message,'error');event.target.disabled=false}});
load().catch(error=>msg(error.message,'error'));
