const $=(id)=>document.getElementById(id);
const loginPanel=$("loginPanel"),setupPanel=$("setupPanel"),dashboardPanel=$("dashboardPanel"),loginForm=$("loginForm"),loginMessage=$("loginMessage"),adminEmail=$("adminEmail"),databaseStatus=$("databaseStatus"),logoutButton=$("logoutButton"),openCategoriesButton=$("openCategoriesButton"),categoriesPanel=$("categoriesPanel"),categoryRows=$("categoryRows"),categoryCount=$("categoryCount"),categoryMessage=$("categoryMessage"),newCategoryButton=$("newCategoryButton"),importCategoriesButton=$("importCategoriesButton"),categoryDialog=$("categoryDialog"),categoryForm=$("categoryForm"),closeDialogButton=$("closeDialogButton"),cancelDialogButton=$("cancelDialogButton"),formMessage=$("formMessage"),dialogTitle=$("dialogTitle");
let categories=[];
function show(panel){[loginPanel,setupPanel,dashboardPanel].forEach(x=>x.classList.add("hidden"));panel.classList.remove("hidden")}
function setMessage(el,msg="",type="success"){el.textContent=msg;el.className=msg?`status ${type}`:"status hidden"}
function escapeHtml(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c])}
function slugify(v){return String(v||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").replace(/-{2,}/g,"-")}
async function api(url,options={}){const r=await fetch(url,{cache:"no-store",credentials:"same-origin",...options,headers:{"content-type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(r.status===401){show(loginPanel);throw new Error("เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่")}if(!r.ok)throw new Error(d.error||"เกิดข้อผิดพลาด");return d}
async function getSession(){const r=await fetch("/api/admin/session",{cache:"no-store",credentials:"same-origin"});const d=await r.json().catch(()=>({}));if(r.status===503&&d.configured===false)return show(setupPanel);if(!r.ok||!d.authenticated){localStorage.removeItem("toyskub_admin_ui");return show(loginPanel)}localStorage.setItem("toyskub_admin_ui","1");adminEmail.textContent=d.admin?.email||"เจ้าของเว็บไซต์";databaseStatus.textContent=d.database?.connected?"TOYSKUB_DB เชื่อมต่อแล้ว":"TOYSKUB_DB ยังไม่เชื่อมต่อ";show(dashboardPanel);await loadCategories(false)}
async function loadCategories(showPanel=true){if(showPanel){categoriesPanel.classList.remove("hidden");categoriesPanel.scrollIntoView({behavior:"smooth",block:"start"})}categoryRows.innerHTML='<tr><td colspan="6">กำลังโหลดข้อมูล…</td></tr>';try{const d=await api("/api/admin/categories");categories=d.categories||[];categoryCount.textContent=`${categories.length} รายการ`;renderCategories()}catch(e){categoryRows.innerHTML=`<tr><td colspan="6">${escapeHtml(e.message)}</td></tr>`;setMessage(categoryMessage,e.message,"error")}}
function childrenOf(parentId){return categories.filter(c=>(c.parentId??null)===(parentId??null)).sort((a,b)=>(a.sortOrder-b.sortOrder)||a.name.localeCompare(b.name))}
function flatten(parentId=null,depth=0,out=[]){for(const c of childrenOf(parentId)){out.push({...c,depth});flatten(c.id,depth+1,out)}return out}
function typeLabel(t){return t==="grade"?"เกรด":t==="product_type"?"ประเภท":"หมวดหลัก"}
function renderCategories(){const rows=flatten();if(!rows.length){categoryRows.innerHTML='<tr><td colspan="6">ยังไม่มีหมวด กด “นำเข้าหมวดเดิม” เพื่อดึง Gundam → Gunpla → RG/MG/HG</td></tr>';return}categoryRows.innerHTML=rows.map(c=>`<tr><td><div class="move-buttons"><button data-up="${c.id}" title="เลื่อนขึ้น">↑</button><button data-down="${c.id}" title="เลื่อนลง">↓</button></div></td><td><div class="tree-name tree-indent-${Math.min(c.depth,2)}"><b>${escapeHtml(c.name)}</b></div><small>${escapeHtml(c.sourcePath||c.description||"")}</small></td><td><span class="type-badge">${typeLabel(c.nodeType)}</span></td><td><code>${escapeHtml(c.slug)}</code></td><td><span class="badge ${c.isActive?"active":"inactive"}">${c.isActive?"ใช้งาน":"ซ่อน"}</span></td><td><div class="row-actions"><button data-edit="${c.id}">แก้ไข</button><button class="danger" data-delete="${c.id}">ลบ</button></div></td></tr>`).join("")}
function populateParents(current=null){const sel=$("categoryParent");sel.innerHTML='<option value="">— หมวดหลัก —</option>'+flatten().filter(c=>!current||c.id!==current.id).map(c=>`<option value="${c.id}">${"— ".repeat(c.depth)}${escapeHtml(c.name)}</option>`).join("")}
function openCategoryDialog(c=null){categoryForm.reset();setMessage(formMessage);$("categoryId").value=c?.id||"";$("categoryName").value=c?.name||"";$("categorySlug").value=c?.slug||"";$("categoryDescription").value=c?.description||"";$("categorySortOrder").value=c?.sortOrder??0;$("categoryActive").checked=c?Boolean(c.isActive):true;$("categoryNodeType").value=c?.nodeType||"category";populateParents(c);$("categoryParent").value=c?.parentId||"";dialogTitle.textContent=c?"แก้ไขหมวด":"เพิ่มหมวด";categoryDialog.showModal()}
async function moveCategory(id,direction){const c=categories.find(x=>Number(x.id)===Number(id));if(!c)return;const siblings=childrenOf(c.parentId);const i=siblings.findIndex(x=>x.id===c.id),j=i+direction;if(j<0||j>=siblings.length)return;[siblings[i],siblings[j]]=[siblings[j],siblings[i]];await api("/api/admin/categories/reorder",{method:"POST",body:JSON.stringify({ids:siblings.map(x=>x.id)})});await loadCategories(false)}
loginForm.addEventListener("submit",async e=>{e.preventDefault();setMessage(loginMessage,"กำลังเข้าสู่ระบบ…","loading");try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:$("password").value})});localStorage.setItem("toyskub_admin_ui","1");await getSession()}catch(err){setMessage(loginMessage,err.message,"error")}});
logoutButton.addEventListener("click",async()=>{await fetch("/api/admin/logout",{method:"POST",credentials:"same-origin"});localStorage.removeItem("toyskub_admin_ui");show(loginPanel)});openCategoriesButton.addEventListener("click",()=>loadCategories(true));newCategoryButton.addEventListener("click",()=>openCategoryDialog());closeDialogButton.addEventListener("click",()=>categoryDialog.close());cancelDialogButton.addEventListener("click",()=>categoryDialog.close());
importCategoriesButton.addEventListener("click",async()=>{if(!confirm("นำเข้าหมวดเดิมจาก categories.json เข้า D1 หรือไม่? ระบบจะไม่สร้างรายการซ้ำ"))return;setMessage(categoryMessage,"กำลังนำเข้าหมวดเดิม…","loading");try{const d=await api("/api/admin/categories/import",{method:"POST",body:"{}"});setMessage(categoryMessage,d.message||"นำเข้าเรียบร้อย","success");await loadCategories(false)}catch(e){setMessage(categoryMessage,e.message,"error")}});
$("categoryName").addEventListener("input",e=>{const s=$("categorySlug");if(!s.dataset.edited)s.value=slugify(e.target.value)});$("categorySlug").addEventListener("input",e=>{e.target.dataset.edited=e.target.value?"1":"";e.target.value=slugify(e.target.value)});
categoryRows.addEventListener("click",async e=>{if(e.target.dataset.up)return moveCategory(Number(e.target.dataset.up),-1);if(e.target.dataset.down)return moveCategory(Number(e.target.dataset.down),1);const edit=Number(e.target.dataset.edit),del=Number(e.target.dataset.delete);if(edit)return openCategoryDialog(categories.find(x=>Number(x.id)===edit));if(!del)return;const c=categories.find(x=>Number(x.id)===del);if(!confirm(`ลบ “${c?.name||"รายการนี้"}” หรือไม่?`))return;try{await api(`/api/admin/categories/${del}`,{method:"DELETE"});await loadCategories(false)}catch(err){setMessage(categoryMessage,err.message,"error")}});
categoryForm.addEventListener("submit",async e=>{e.preventDefault();const id=$("categoryId").value,payload={name:$("categoryName").value,slug:$("categorySlug").value,description:$("categoryDescription").value,sortOrder:Number($("categorySortOrder").value)||0,isActive:$("categoryActive").checked,nodeType:$("categoryNodeType").value,parentId:$("categoryParent").value?Number($("categoryParent").value):null};setMessage(formMessage,"กำลังบันทึก…","loading");try{await api(id?`/api/admin/categories/${id}`:"/api/admin/categories",{method:id?"PUT":"POST",body:JSON.stringify(payload)});categoryDialog.close();await loadCategories(true)}catch(err){setMessage(formMessage,err.message,"error")}});
void getSession();

// PART 2.2 — MEMBER MANAGER
const openMembersButton=document.getElementById("openMembersButton"),membersPanel=document.getElementById("membersPanel"),memberRows=document.getElementById("memberRows"),memberCount=document.getElementById("memberCount"),memberMessage=document.getElementById("memberMessage");
async function loadMembers(){membersPanel.classList.remove("hidden");membersPanel.scrollIntoView({behavior:"smooth",block:"start"});memberRows.innerHTML='<tr><td colspan="7">กำลังโหลดข้อมูล…</td></tr>';try{const d=await api('/api/admin/members');const rows=d.members||[];memberCount.textContent=`${rows.length} คน`;memberRows.innerHTML=rows.length?rows.map(m=>`<tr><td>${m.id}</td><td>${escapeHtml(m.displayName||`${m.firstName||''} ${m.lastName||''}`.trim()||'-')}</td><td>${escapeHtml(m.email)}</td><td>${escapeHtml(m.phone||'-')}</td><td><span class="badge">${escapeHtml(m.role)}</span></td><td>${escapeHtml(m.status)}</td><td>${escapeHtml(m.createdAt||'-')}</td></tr>`).join(''):'<tr><td colspan="7">ยังไม่มีสมาชิก</td></tr>'}catch(e){memberRows.innerHTML=`<tr><td colspan="7">${escapeHtml(e.message)}</td></tr>`;setMessage(memberMessage,e.message,'error')}}
if(openMembersButton)openMembersButton.addEventListener('click',loadMembers);
