const $=id=>document.getElementById(id);let items=[],editing=null;
const fields=['id','sku','name','rgNumber','categoryLabel','categoryCode','productType','productTypeCode','line','lineCode','seriesGroup','seriesGroupOrder','series','scale','manufacturer','releaseDate','launchPriceJPY','recommendedAge','modelCode','catalogImage','images','summary','highlights','whatsDifferent','boxContents','pros','considerations','faq','manualImages','videoEmbedUrl','sourceName','sourceUrl','status','sortOrder'];
function msg(t='',type='success'){const e=$('message');e.textContent=t;e.className=t?`status ${type}`:'status hidden'}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function code(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
async function api(u,o={}){const r=await fetch(u,{cache:'no-store',...o,headers:{'content-type':'application/json',...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(r.status===401){location.href='/admin/';throw Error('กรุณาเข้าสู่ระบบใหม่')}if(!r.ok)throw Error(d.error||'เกิดข้อผิดพลาด');return d}
async function load(){const d=await api('/api/admin/catalog');items=d.items||[];render()}
function render(){const q=$('search').value.toLowerCase();const list=items.filter(x=>`${x.id} ${x.name} ${x.line||x.grade||''} ${x.seriesGroup||''} ${x.series||''}`.toLowerCase().includes(q));$('rows').innerHTML=list.length?list.map(x=>`<tr><td>${x.catalogImage?`<img class="thumb" src="/${esc(x.catalogImage).replace(/^\//,'')}" onerror="this.style.visibility='hidden'">`:'—'}</td><td><b>${esc(x.id)}</b><br>${esc(x.name)}</td><td><b>${esc(x.line||x.grade||'—')}</b>${x.seriesGroup?`<br><small>กลุ่ม: ${esc(x.seriesGroup)}</small>`:''}${x.series?`<br><small>${esc(x.series)}</small>`:''}</td><td><span class="status-pill ${esc(x.status)}">${x.status==='published'?'เผยแพร่':x.status==='hidden'?'ซ่อน':'ฉบับร่าง'}</span></td><td><div class="row-actions"><button data-edit="${esc(x.id)}">แก้ไขฟอร์ม</button><button data-inline="${esc(x.id)}">แก้หน้าเหมือนเว็บ</button><button data-copy="${esc(x.id)}">คัดลอก</button><button data-preview="${esc(x.id)}">ดูหน้าเว็บ</button><button class="danger" data-delete="${esc(x.id)}">ลบ</button></div></td></tr>`).join(''):'<tr><td colspan="5">ยังไม่มีรายการจาก D1 กด “เพิ่มรายการ” เพื่อสร้างรายการแรก</td></tr>'}
function lines(v){return Array.isArray(v)?v.join('\n'):''}
function pairsToLines(v,a,b){return Array.isArray(v)?v.map(x=>`${x?.[a]||''} | ${x?.[b]||''}`.trim()).filter(x=>x!=='|').join('\n'):''}
function parsePairs(v,a,b){return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf('|');return i<0?{[a]:line,[b]:''}:{[a]:line.slice(0,i).trim(),[b]:line.slice(i+1).trim()}}).filter(x=>x[a]||x[b])}
function normalizeYouTubeEmbed(value){const raw=String(value||'').trim();if(!raw)return '';const src=(raw.match(/src=["']([^"']+)["']/i)||[])[1]||raw;try{const u=new URL(src,location.origin);const host=u.hostname.replace(/^www\./,'');let id='';if(host==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0]||'';else if(host==='youtube.com'||host==='m.youtube.com'||host==='youtube-nocookie.com'){if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else{const m=u.pathname.match(/\/(?:embed|shorts|live)\/([^/?]+)/);id=m?.[1]||''}}return id?`https://www.youtube.com/embed/${encodeURIComponent(id)}`:''}catch{return ''}}
function updateLineUI(){const line=$('line').value;const map={RG:'rg',MG:'mg',HG:'hg',PG:'pg',EG:'eg',SD:'sd',FM:'fm',MGEX:'mgex'};if(line!=='OTHER')$('lineCode').value=map[line]||code(line);const group=$('seriesGroup');if(!group.value){group.value=line==='RG'?'Gundam':line==='HG'?'HGUC':''}group.placeholder=line==='RG'?'Gundam, Evangelion, Gaogaigar, Patlabor, Special Version':line==='HG'?'HGUC, HGCE, HGIBO, HGBF, HGBD':'ชื่อกลุ่มที่ต้องการแบ่งในหน้าเดียว (เว้นว่างได้)';$('series').placeholder='ชื่อเรื่องหรือจักรวาลต้นฉบับ เช่น Mobile Suit Gundam SEED'}
function openEditor(p=null,copy=false){editing=copy?null:p?.id||null;$('form').reset();$('categoryLabel').value='Gundam';$('categoryCode').value='gd';$('productType').value='Gunpla';$('productTypeCode').value='gp';$('line').value='RG';$('lineCode').value='rg';$('scale').value='1/144';$('manufacturer').value='Bandai Spirits';$('status').value='draft';$('sortOrder').value='0';if(p){const normalized={...p,line:p.line||p.grade||'RG',categoryCode:p.categoryCode||'gd',productTypeCode:p.productTypeCode||'gp'};for(const k of fields){if($(k))$(k).value=['images','highlights','boxContents','pros','considerations','manualImages'].includes(k)?lines(normalized[k]):k==='whatsDifferent'?pairsToLines(normalized[k],'title','detail'):k==='faq'?pairsToLines(normalized[k],'q','a'):normalized[k]??''}$('shopee').value=p.affiliateLinks?.shopee||'';$('lazada').value=p.affiliateLinks?.lazada||'';if(copy){$('id').value='';$('sku').value='';$('name').value=`${p.name} (คัดลอก)`}}$('id').disabled=Boolean(editing);$('editorTitle').textContent=editing?'แก้ไขรายการ':copy?'คัดลอกรายการ':'เพิ่มรายการแคตตาล็อก';updateLineUI();$('editor').classList.remove('hidden');$('editor').scrollIntoView({behavior:'smooth'})}
function payload(){const p={};for(const k of fields)p[k]=$(k).value;p.categoryCode=code(p.categoryCode);p.productTypeCode=code(p.productTypeCode);p.lineCode=code(p.lineCode);p.grade=p.line;p.rgNumber=p.rgNumber?Number(p.rgNumber):null;p.launchPriceJPY=p.launchPriceJPY?Number(p.launchPriceJPY):null;p.sortOrder=Number(p.sortOrder)||0;p.seriesGroupOrder=Number(p.seriesGroupOrder)||0;for(const k of ['images','highlights','boxContents','pros','considerations','manualImages'])p[k]=$(k).value.split('\n').map(x=>x.trim()).filter(Boolean);p.whatsDifferent=parsePairs($('whatsDifferent').value,'title','detail');p.faq=parsePairs($('faq').value,'q','a');p.videoEmbedUrl=normalizeYouTubeEmbed($('videoEmbedUrl').value);p.category='model';p.affiliateLinks={shopee:$('shopee').value.trim(),lazada:$('lazada').value.trim(),tiktok:'',page:''};p.catalogStatus=p.status==='published'?'published':'draft';return p}
$('categoryLabel').oninput=()=>{if(!$('categoryCode').dataset.touched)$('categoryCode').value=$('categoryLabel').value.toLowerCase()==='gundam'?'gd':code($('categoryLabel').value)};
$('productType').oninput=()=>{if(!$('productTypeCode').dataset.touched)$('productTypeCode').value=$('productType').value.toLowerCase()==='gunpla'?'gp':code($('productType').value)};
for(const id of ['categoryCode','productTypeCode','lineCode'])$(id).oninput=e=>{e.target.dataset.touched='1';e.target.value=code(e.target.value)};
$('line').onchange=updateLineUI;
$('newBtn').onclick=()=>openEditor();$('closeBtn').onclick=()=>$('editor').classList.add('hidden');$('search').oninput=render;$('rows').onclick=async e=>{const id=e.target.dataset.edit||e.target.dataset.inline||e.target.dataset.copy||e.target.dataset.preview||e.target.dataset.delete;if(!id)return;if(e.target.dataset.inline){location.href=`/admin/rg-template/?id=${encodeURIComponent(id)}`;return}if(e.target.dataset.preview){window.open(`/#/product/${id}`,'_blank');return}if(e.target.dataset.delete){if(confirm(`ลบ ${id} หรือไม่?`)){await api(`/api/admin/catalog/${id}`,{method:'DELETE'});await load()}return}const d=await api(`/api/admin/catalog/${id}`);openEditor(d.item,Boolean(e.target.dataset.copy))};
$('form').onsubmit=async e=>{e.preventDefault();msg('กำลังบันทึก…','loading');try{const rawVideo=$('videoEmbedUrl').value.trim();if(rawVideo&&!normalizeYouTubeEmbed(rawVideo))throw Error('ช่อง YouTube ต้องเป็นลิงก์ YouTube หรือโค้ด iframe ของ YouTube เท่านั้น');await api(editing?`/api/admin/catalog/${editing}`:'/api/admin/catalog',{method:editing?'PUT':'POST',body:JSON.stringify(payload())});msg('บันทึกเรียบร้อย');$('editor').classList.add('hidden');await load()}catch(err){msg(err.message,'error')}};$('previewBtn').onclick=()=>{const rawVideo=$('videoEmbedUrl').value.trim();if(rawVideo&&!normalizeYouTubeEmbed(rawVideo)){msg('ช่อง YouTube ต้องเป็นลิงก์ YouTube หรือโค้ด iframe ของ YouTube เท่านั้น','error');return}const p=payload();localStorage.setItem('toyskub_catalog_preview',JSON.stringify(p));window.open('/#/product-preview','_blank')};updateLineUI();load().catch(e=>msg(e.message,'error'));
